### ISSUE TITLE
Checkbox array

### ISSUE THREAD

**Issue by jhemmmm** [hartwork/vue-tristate-checkbox#1]
Hello,

I want to create a multiple checkbox with the same name/v-model.

**Comment by hartwork** [comment]
Hi! What have you tried? What is the problem?

**Comment by jhemmmm** [comment]
I'll be closing this issue since I have fixed it on my own way.

I tried using an object to the v-model that get the included/excluded checkboxes.

**Comment by hartwork** [comment]
Okay, thanks for the update!
